# .github/workflows/deploy.yml
name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          auto-activate-base: false

      - name: Create and activate Conda environment
        run: |
          conda create -y -n ai4c-papers python=3.10
          source "$(dirname $(dirname $(which conda)))/etc/profile.d/conda.sh"
          conda activate ai4c-papers

      - name: Install Python dependencies
        run: |
          pip install bibtexparser

      - name: Generate Markdown and JSON
        working-directory: scripts
        run: |
          python 01-bib2md.py
          python 02-bib2json.py

      - name: Prepare public folder
        run: |
          rm -rf public
          mkdir public
          cp -r scripts/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/${{ github.repository }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1